# Connect config
me:
    name: cheetah.
    description: jThIRC
    sid: 5PC
    protocolversion: "6000"
    versionflags: ""
    fullversiontext: jThIRC
    
database:
    path: "db/qbot.sqlite3"

admin:
    - line 1
    - line 2
    - line 3

link:
    #peer: ocelot.
    #host: polaris3.thibland.net
    host: 192.168.10.1
    port: 6900
    incoming: incoming.host.or.ip
    # Auth by cert => we set password to *
    password: "*"

network:
    name: Mjav

features:
    sasl: no

logging:
    debugIn: no
    debugOut: no

ssl:
    keystore:
        path: "/home/thib/.keystore"
        password: "123456"
    truststore:
        path: "/home/thib/.keystore"
        password: "123456"

cservice:
    enable: yes
    nick: Q
    uniq: AAAAAA
    ident: qbot
    host: CServe
    realname: The Q Bot
    modes: +ioqBS
    accountsettings:
        passlen: 12
        autolimitinterval: 60
        chanophistory: 10
        maxchannels: 500
        lastreg: 100
        authvhostprefix: "user/"
        authvhostsuffix: ""
    chansettings:
        emaillen: 60
        welcomelen: 250
        infolen: 100
        maxchanlevs: 500
        maxbans: 100
